const toolCatalog = {
  Electrician: {
    Screwdrivers: [
      "Flathead Screwdriver 2.5 mm",
      "Flathead Screwdriver 4.0 mm",
      "Flathead Screwdriver 5.5 mm",
      "Flathead Screwdriver 6.5 mm",
      "Phillips Screwdriver PH1",
      "Phillips Screwdriver PH2",
      "Phillips Screwdriver PH3",
      "Pozidriv Screwdriver PZ1",
      "Pozidriv Screwdriver PZ2",
      "Torx Screwdriver T10",
      "Torx Screwdriver T15",
      "Torx Screwdriver T20",
      "Insulated Flathead Screwdriver",
      "Insulated Phillips Screwdriver",
      "Precision Screwdriver Set",
      "Voltage Tester Screwdriver",
    ],

    PowerTools: [
      "Makita Cordless Drill",
      "Makita Impact Driver",
      "Makita Angle Grinder",
      "Makita Rotary Hammer",
      "Bosch Hammer Drill",
      "Milwaukee Impact Driver",
      "Cordless Circular Saw",
      "Cordless Jigsaw",
      "Reciprocating Saw",
      "Oscillating Tool",
      "Heat Gun",
      "Demolition Hammer",
    ],

    BatteriesChargers: [
      "Makita Battery 18V 5Ah",
      "Makita Battery 18V 6Ah",
      "Bosch Battery 18V",
      "DeWalt Battery 20V",
      "Battery Charger",
      "Dual Battery Charger",
      "Battery Powered Work Light",
    ],

    MeasuringTools: [
      "Multimeter",
      "Clamp Meter",
      "Voltage Tester",
      "Non Contact Voltage Tester",
      "Megohmmeter",
      "Laser Distance Meter",
      "Laser Level",
      "Spirit Level",
      "Thermal Camera",
      "Socket Tester",
      "Continuity Tester",
      "Phase Rotation Tester",
    ],

    CableTools: [
      "Cable Cutter",
      "Wire Stripper",
      "Crimping Tool",
      "Hydraulic Crimper",
      "Fish Tape",
      "Cable Puller",
      "Cable Pulling Rod",
      "Cable Reel",
      "Cable Drum",
      "Cable Ties",
      "Electrical Tape",
      "Heat Shrink Tubing",
    ],

    HandTools: [
      "Combination Pliers",
      "Needle Nose Pliers",
      "Side Cutter Pliers",
      "Water Pump Pliers",
      "Adjustable Wrench",
      "Socket Set",
      "Ratchet Set",
      "Torque Wrench",
      "Hex Key Set",
      "Bolt Cutter",
      "Tin Snips",
    ],

    SafetyEquipment: [
      "Work Gloves",
      "Insulated Gloves",
      "Safety Glasses",
      "Face Shield",
      "Ear Protection",
      "Dust Mask",
      "Hard Hat",
      "Headlamp",
    ],

    InstallationMaterials: [
      "Terminal Block",
      "Cable Lug",
      "Junction Box",
      "Distribution Box",
      "Circuit Breaker",
      "Fuse Holder",
      "DIN Rail",
      "Contactors",
      "Relays",
      "Push Buttons",
      "Emergency Stop Button",
      "Industrial Plug",
      "Industrial Socket",
      "Wall Socket",
      "Light Switch",
      "Dimmer Switch",
      "Motion Sensor",
    ],

    Lighting: [
      "LED Panel",
      "LED Strip",
      "Flood Light",
      "Ceiling Light",
      "Portable Work Light",
    ],

    IndustrialSolar: [
      "Portable Generator",
      "UPS System",
      "Solar Inverter",
      "Solar Panel Tester",
      "PVC Conduit",
      "Metal Conduit",
      "Cable Tray",
      "Scaffold",
      "Extension Ladder",
      "Step Ladder",
    ],
  },

  Plumber: {
    MainTools: [
      "Pipe Cutter",
      "Pipe Wrench",
      "Adjustable Wrench",
      "Press Tool",
      "Drain Cleaner",
      "Water Pump Pliers",
      "Threading Machine",
      "Crimping Tool",
      "Tube Bender",
      "Inspection Camera",
    ],
  },

  Carpenter: {
    MainTools: [
      "Circular Saw",
      "Jigsaw",
      "Orbital Sander",
      "Nail Gun",
      "Chisel Set",
      "Tape Measure",
      "Spirit Level",
      "Table Saw",
      "Router",
      "Clamp Set",
    ],
  },

  Painter: {
    MainTools: [
      "Paint Roller",
      "Paint Brush",
      "Spray Gun",
      "Paint Mixer",
      "Ladder",
      "Masking Tape",
      "Putty Knife",
      "Sanding Block",
      "Extension Pole",
      "Drop Cloth",
    ],
  },
};

export default toolCatalog;