const toolCatalog = {
  Electrician: {
    Screwdrivers: [
      "Flathead Screwdriver 2.5 mm",
      "Flathead Screwdriver 4.0 mm",
      "Flathead Screwdriver 5.5 mm",
      "Flathead Screwdriver 6.5 mm",
      "Flathead Screwdriver 8.0 mm",
      "Phillips Screwdriver PH0",
      "Phillips Screwdriver PH1",
      "Phillips Screwdriver PH2",
      "Phillips Screwdriver PH3",
      "Pozidriv Screwdriver PZ1",
      "Pozidriv Screwdriver PZ2",
      "Pozidriv Screwdriver PZ3",
      "Torx Screwdriver T6",
      "Torx Screwdriver T8",
      "Torx Screwdriver T10",
      "Torx Screwdriver T15",
      "Torx Screwdriver T20",
      "Torx Screwdriver T25",
      "Torx Screwdriver T30",
      "Insulated Flathead Screwdriver 1000V",
      "Insulated Phillips Screwdriver 1000V",
      "Insulated Pozidriv Screwdriver 1000V",
      "Precision Screwdriver Set",
      "Voltage Tester Screwdriver",
      "Magnetic Screwdriver Set",
      "Ratchet Screwdriver",
      "Stubby Screwdriver Set",
      "Long Reach Screwdriver Set",
      "Nut Driver 5.5 mm",
      "Nut Driver 7.0 mm",
      "Nut Driver 8.0 mm",
      "Nut Driver 10.0 mm",
    ],
    PowerTools: [
      "Makita Cordless Drill 18V",
      "Makita Impact Driver 18V",
      "Makita Angle Grinder 125mm",
      "Makita Angle Grinder 115mm",
      "Makita Rotary Hammer SDS+",
      "Makita Cordless Circular Saw",
      "Makita Cordless Jigsaw",
      "Makita Cordless Reciprocating Saw",
      "Makita Oscillating Tool",
      "Makita Heat Gun",
      "Makita Demolition Hammer",
      "Bosch Hammer Drill",
      "Bosch Impact Driver",
      "Bosch Angle Grinder",
      "Bosch Rotary Hammer SDS+",
      "Bosch Cordless Drill",
      "Milwaukee Impact Driver",
      "Milwaukee Hammer Drill",
      "Milwaukee Angle Grinder",
      "DeWalt Cordless Drill",
      "DeWalt Impact Driver",
      "DeWalt Angle Grinder",
      "Hilti Cordless Drill",
      "Hilti Rotary Hammer",
      "Cordless Screwdriver",
      "Right Angle Drill",
      "Magnetic Drill",
      "Core Drill",
      "Wall Chaser",
      "Pipe Threading Machine",
    ],
    BatteriesChargers: [
      "Makita Battery 18V 3Ah",
      "Makita Battery 18V 5Ah",
      "Makita Battery 18V 6Ah",
      "Makita Battery 36V",
      "Makita Battery Charger DC18RC",
      "Makita Dual Battery Charger",
      "Bosch Battery 18V 2Ah",
      "Bosch Battery 18V 4Ah",
      "Bosch Battery 18V 6Ah",
      "Bosch Battery Charger",
      "Milwaukee Battery M18 5Ah",
      "Milwaukee Battery M18 9Ah",
      "Milwaukee Battery Charger",
      "DeWalt Battery 20V 5Ah",
      "DeWalt Battery Charger",
      "Hilti Battery 22V",
      "Hilti Battery Charger",
      "Battery Powered Work Light",
      "Portable Power Station",
      "USB Battery Charger",
    ],
    MeasuringTools: [
      "Digital Multimeter",
      "Analog Multimeter",
      "Clamp Meter AC/DC",
      "Clamp Meter AC",
      "Voltage Tester",
      "Non Contact Voltage Tester",
      "Phase Tester",
      "Phase Rotation Tester",
      "Megohmmeter 500V",
      "Megohmmeter 1000V",
      "Earth Resistance Tester",
      "Insulation Resistance Tester",
      "Loop Impedance Tester",
      "Power Quality Analyzer",
      "Energy Meter",
      "Thermal Camera",
      "Laser Distance Meter",
      "Laser Level",
      "Spirit Level 40cm",
      "Spirit Level 60cm",
      "Spirit Level 100cm",
      "Tape Measure 5m",
      "Tape Measure 8m",
      "Tape Measure 10m",
      "Socket Tester",
      "Continuity Tester",
      "RCD Tester",
      "PAT Tester",
      "Oscilloscope",
      "Data Logger",
      "Sound Level Meter",
      "Lux Meter",
    ],
    CableTools: [
      "Cable Cutter 16mm",
      "Cable Cutter 35mm",
      "Cable Cutter 70mm",
      "Cable Cutter 120mm",
      "Wire Stripper Automatic",
      "Wire Stripper Manual",
      "Coaxial Cable Stripper",
      "Cable Crimping Tool",
      "Hydraulic Crimper 10-300mm",
      "Ratchet Crimping Tool",
      "Fish Tape 20m",
      "Fish Tape 30m",
      "Fish Tape Fiberglass",
      "Cable Puller Electric",
      "Cable Pulling Rod Set",
      "Cable Reel 50m",
      "Cable Reel 100m",
      "Cable Drum Stand",
      "Cable Drum Jack",
      "Conduit Bender 20mm",
      "Conduit Bender 25mm",
      "Conduit Bender 32mm",
      "Conduit Bender 40mm",
      "Cable Ties Black 100pcs",
      "Cable Ties White 100pcs",
      "Cable Tie Gun",
      "Electrical Tape Roll",
      "Self-Amalgamating Tape",
      "Heat Shrink Tubing Set",
      "Wire Ferrule Crimper",
      "Ferrule Set Assorted",
      "Terminal Crimping Tool",
    ],
    HandTools: [
      "Combination Pliers 160mm",
      "Combination Pliers 200mm",
      "Needle Nose Pliers",
      "Round Nose Pliers",
      "Side Cutter Pliers",
      "End Cutter Pliers",
      "Water Pump Pliers 250mm",
      "Water Pump Pliers 300mm",
      "Insulated Pliers Set 1000V",
      "Adjustable Wrench 150mm",
      "Adjustable Wrench 200mm",
      "Adjustable Wrench 250mm",
      "Socket Set 1/4",
      "Socket Set 3/8",
      "Socket Set 1/2",
      "Ratchet Handle 1/4",
      "Ratchet Handle 3/8",
      "Ratchet Handle 1/2",
      "Torque Wrench 10-60Nm",
      "Torque Wrench 20-110Nm",
      "Hex Key Set Metric",
      "Hex Key Set Imperial",
      "T-Handle Hex Key Set",
      "Ball-End Hex Key Set",
      "Bolt Cutter 600mm",
      "Tin Snips Straight",
      "Tin Snips Left",
      "Tin Snips Right",
      "Hammer 300g",
      "Rubber Mallet",
      "Utility Knife",
      "Hacksaw",
      "Junior Hacksaw",
      "File Set",
      "Punch Set",
      "Chisel Set",
      "Pry Bar",
      "Crowbar",
    ],
    SafetyEquipment: [
      "Work Gloves Leather",
      "Work Gloves Nitrile",
      "Insulated Gloves Class 00",
      "Insulated Gloves Class 0",
      "Insulated Gloves Class 1",
      "Insulated Gloves Class 2",
      "Safety Glasses Clear",
      "Safety Glasses Dark",
      "Face Shield",
      "Welding Shield",
      "Ear Protection Plugs",
      "Ear Protection Muffs",
      "Dust Mask FFP1",
      "Dust Mask FFP2",
      "Dust Mask FFP3",
      "Half Face Respirator",
      "Full Face Respirator",
      "Hard Hat White",
      "Hard Hat Yellow",
      "Headlamp",
      "High Vis Vest",
      "Safety Boots",
      "Knee Pads",
      "Safety Harness",
      "Fall Arrest Lanyard",
      "First Aid Kit",
      "Fire Extinguisher",
    ],
    InstallationMaterials: [
      "Terminal Block 2.5mm",
      "Terminal Block 4mm",
      "Terminal Block 6mm",
      "Terminal Block 10mm",
      "Terminal Block 16mm",
      "Cable Lug 6mm",
      "Cable Lug 10mm",
      "Cable Lug 16mm",
      "Cable Lug 25mm",
      "Cable Lug 35mm",
      "Cable Lug 50mm",
      "Junction Box IP54",
      "Junction Box IP65",
      "Distribution Box 4 Way",
      "Distribution Box 8 Way",
      "Distribution Box 12 Way",
      "MCB Circuit Breaker 6A",
      "MCB Circuit Breaker 10A",
      "MCB Circuit Breaker 16A",
      "MCB Circuit Breaker 20A",
      "MCB Circuit Breaker 25A",
      "MCB Circuit Breaker 32A",
      "MCB Circuit Breaker 40A",
      "MCB Circuit Breaker 63A",
      "RCD 25A 30mA",
      "RCD 40A 30mA",
      "RCD 63A 30mA",
      "RCBO 16A",
      "RCBO 20A",
      "RCBO 32A",
      "Fuse Holder",
      "Fuse 6A",
      "Fuse 10A",
      "Fuse 16A",
      "Fuse 25A",
      "DIN Rail 35mm",
      "DIN Rail End Cap",
      "Contactor 9A",
      "Contactor 12A",
      "Contactor 18A",
      "Contactor 25A",
      "Contactor 32A",
      "Relay 24V",
      "Relay 230V",
      "Timer Relay",
      "Overload Relay",
      "Push Button Green",
      "Push Button Red",
      "Emergency Stop Button",
      "Selector Switch",
      "Indicator Light Red",
      "Indicator Light Green",
      "Industrial Plug 16A",
      "Industrial Plug 32A",
      "Industrial Socket 16A",
      "Industrial Socket 32A",
      "Wall Socket",
      "Wall Socket with USB",
      "Double Socket",
      "Waterproof Socket IP44",
      "Light Switch",
      "Double Switch",
      "Dimmer Switch",
      "Motion Sensor",
      "PIR Sensor",
      "Smoke Detector",
      "CO Detector",
    ],
    Lighting: [
      "LED Panel 60x60",
      "LED Panel 30x120",
      "LED Downlight 10W",
      "LED Downlight 20W",
      "LED Strip 5m",
      "LED Strip Controller",
      "LED Flood Light 50W",
      "LED Flood Light 100W",
      "LED Flood Light 200W",
      "LED Street Light",
      "LED High Bay 100W",
      "LED High Bay 200W",
      "Ceiling Light",
      "Pendant Light",
      "Emergency Light",
      "Exit Sign Light",
      "Portable Work Light",
      "Tripod Work Light",
      "Headlamp LED",
      "Torch LED",
    ],
    LaddersAccess: [
      "Extension Ladder 3m",
      "Extension Ladder 4m",
      "Extension Ladder 5m",
      "Extension Ladder 6m",
      "Extension Ladder 8m",
      "Step Ladder 1m",
      "Step Ladder 1.5m",
      "Step Ladder 2m",
      "Step Ladder 2.5m",
      "Step Ladder 3m",
      "Combination Ladder",
      "Platform Ladder",
      "Scaffold Tower",
      "Mobile Scaffold",
    ],
    CablesConduits: [
      "PVC Conduit 20mm",
      "PVC Conduit 25mm",
      "PVC Conduit 32mm",
      "PVC Conduit 40mm",
      "Metal Conduit 20mm",
      "Metal Conduit 25mm",
      "Flexible Conduit 20mm",
      "Flexible Conduit 25mm",
      "Cable Tray 50mm",
      "Cable Tray 100mm",
      "Cable Tray 200mm",
      "Cable Basket",
      "Cable Duct 40x25",
      "Cable Duct 60x40",
      "Cable Duct 80x60",
    ],
  },

  Plumber: {
    PipeCuttingTools: [
      "Pipe Cutter 3-35mm",
      "Pipe Cutter 15-64mm",
      "Pipe Cutter 40-110mm",
      "Pipe Cutter Copper",
      "Pipe Cutter Stainless",
      "Pipe Saw",
      "Angle Grinder with Cutting Disc",
      "Reciprocating Saw",
      "Pipe Shears 15-35mm",
      "Pipe Shears 35-70mm",
      "Plastic Pipe Cutter",
      "Hacksaw",
    ],
    PipeWorkingTools: [
      "Pipe Wrench 250mm",
      "Pipe Wrench 300mm",
      "Pipe Wrench 350mm",
      "Pipe Wrench 450mm",
      "Chain Wrench",
      "Strap Wrench",
      "Pipe Bender 15mm",
      "Pipe Bender 22mm",
      "Pipe Bender 28mm",
      "Hydraulic Pipe Bender",
      "Electric Pipe Bender",
      "Pipe Threading Machine",
      "Manual Pipe Threader",
      "Pipe Reamer",
      "Pipe Deburrer",
      "Pipe Beveler",
      "Pipe Expander",
      "Press Tool Electric",
      "Press Tool Battery",
      "Press Jaw 15mm",
      "Press Jaw 22mm",
      "Press Jaw 28mm",
      "Press Jaw 35mm",
      "Press Jaw 42mm",
      "Press Jaw 54mm",
      "Crimping Tool",
      "Compression Fitting Tool",
    ],
    DrainageTools: [
      "Drain Snake 15m",
      "Drain Snake 30m",
      "Electric Drain Cleaner",
      "High Pressure Jetter",
      "Drain Inspection Camera",
      "Drain Camera 30m",
      "Drain Plunger",
      "Drain Unblocker",
      "Manhole Cover Lifter",
      "Drain Rod Set",
      "Pipe Locator",
      "Leak Detector",
    ],
    SolderingWelding: [
      "Blow Torch Propane",
      "Blow Torch MAPP",
      "Gas Cylinder Propane",
      "Gas Cylinder MAPP",
      "Solder Wire",
      "Flux Paste",
      "Brazing Rod",
      "Welding Machine MIG",
      "Welding Machine TIG",
      "Welding Mask",
      "Welding Gloves",
      "Fire Blanket",
    ],
    MeasuringTools: [
      "Digital Pressure Gauge",
      "Analog Pressure Gauge",
      "Pressure Test Kit",
      "Flow Meter",
      "Water Meter",
      "Thermometer Digital",
      "Infrared Thermometer",
      "Leak Detection Spray",
      "Gas Leak Detector",
      "Moisture Meter",
      "Manometer",
      "Tape Measure 5m",
      "Tape Measure 8m",
      "Spirit Level",
      "Laser Level",
    ],
    HandTools: [
      "Adjustable Wrench 200mm",
      "Adjustable Wrench 300mm",
      "Combination Spanner Set",
      "Open End Spanner Set",
      "Ring Spanner Set",
      "Socket Set",
      "Torque Wrench",
      "Basin Wrench",
      "Radiator Wrench",
      "Combination Pliers",
      "Water Pump Pliers 250mm",
      "Water Pump Pliers 300mm",
      "Groove Joint Pliers",
      "Needle Nose Pliers",
      "Hammer",
      "Rubber Mallet",
      "Chisel",
      "Punch Set",
      "Hacksaw",
      "Utility Knife",
      "Putty Knife",
      "Scraper",
    ],
    PowerTools: [
      "Cordless Drill",
      "Hammer Drill",
      "Angle Grinder",
      "Reciprocating Saw",
      "Jigsaw",
      "Core Drill",
      "Wall Chaser",
      "Hot Air Gun",
      "Electric Pump",
      "Submersible Pump",
      "Pressure Washer",
    ],
    SafetyEquipment: [
      "Work Gloves",
      "Chemical Resistant Gloves",
      "Safety Glasses",
      "Face Shield",
      "Knee Pads",
      "Safety Boots Waterproof",
      "Dust Mask",
      "Ear Protection",
      "Hard Hat",
      "High Vis Vest",
      "Confined Space Equipment",
      "First Aid Kit",
    ],
    InstallationMaterials: [
      "PTFE Tape",
      "Pipe Thread Sealant",
      "Pipe Jointing Compound",
      "Silicone Sealant",
      "Pipe Insulation 15mm",
      "Pipe Insulation 22mm",
      "Pipe Insulation 28mm",
      "Pipe Insulation 35mm",
      "Pipe Clips 15mm",
      "Pipe Clips 22mm",
      "Pipe Clips 28mm",
      "Pipe Support Bracket",
      "Isolation Valve 15mm",
      "Isolation Valve 22mm",
      "Ball Valve 15mm",
      "Ball Valve 22mm",
      "Ball Valve 28mm",
      "Gate Valve",
      "Check Valve",
      "Pressure Relief Valve",
      "Thermostatic Valve",
      "Radiator Valve",
      "Float Valve",
      "Stop Cock",
    ],
    LaddersAccess: [
      "Step Ladder 1.5m",
      "Step Ladder 2m",
      "Step Ladder 3m",
      "Extension Ladder 4m",
      "Extension Ladder 6m",
      "Platform Ladder",
      "Scaffold Tower",
    ],
  },

  HVAC: {
    RefrigerationTools: [
      "Manifold Gauge Set R32",
      "Manifold Gauge Set R410A",
      "Manifold Gauge Set R134a",
      "Manifold Gauge Set R22",
      "Digital Manifold Gauge",
      "Vacuum Pump 2-Stage",
      "Vacuum Pump 4-Stage",
      "Electronic Vacuum Gauge",
      "Refrigerant Scale",
      "Refrigerant Recovery Machine",
      "Refrigerant Cylinder R32",
      "Refrigerant Cylinder R410A",
      "Refrigerant Cylinder R134a",
      "Charging Hose Set",
      "Quick Connect Hose",
      "Service Valve Tool",
      "Schrader Valve Tool",
    ],
    PipeBendingCutting: [
      "Copper Pipe Cutter 3-35mm",
      "Copper Pipe Cutter 6-67mm",
      "Pipe Bender 1/4",
      "Pipe Bender 3/8",
      "Pipe Bender 1/2",
      "Pipe Bender 5/8",
      "Pipe Bender 3/4",
      "Electric Pipe Bender",
      "Flaring Tool",
      "Swaging Tool",
      "Pipe Expander",
      "Pipe Deburrer",
      "Pipe Reamer",
    ],
    MeasuringTools: [
      "Digital Thermometer",
      "Dual Input Thermometer",
      "Infrared Thermometer",
      "Thermocouple Probe",
      "Anemometer",
      "Air Flow Meter",
      "Manometer Digital",
      "Differential Pressure Meter",
      "Humidity Meter",
      "CO2 Meter",
      "Combustion Analyzer",
      "Leak Detector Electronic",
      "UV Leak Detector",
      "Clamp Meter",
      "Multimeter",
      "Thermal Camera",
      "Psychrometer",
    ],
    InstallationTools: [
      "Pipe Press Tool",
      "Hydraulic Press Tool",
      "Brazing Torch",
      "Gas Cylinder Nitrogen",
      "Nitrogen Regulator",
      "Pressure Test Kit",
      "Vacuum Test Kit",
      "Insulation Knife",
      "Insulation Scissors",
      "Sheet Metal Shears",
      "Tin Snips",
      "Sheet Metal Folder",
      "Pop Rivet Gun",
      "Rivet Set",
      "Sheet Metal Drill Bits",
      "Step Drill Bit",
      "Knockout Punch Set",
      "Cable Ties",
      "Plastic Anchors",
    ],
    PowerTools: [
      "Cordless Drill",
      "Hammer Drill",
      "Angle Grinder",
      "Reciprocating Saw",
      "Jigsaw",
      "Core Drill",
      "Sheet Metal Nibbler",
      "Circular Saw",
    ],
    HandTools: [
      "Adjustable Wrench",
      "Combination Spanner Set",
      "Hex Key Set Metric",
      "Hex Key Set Imperial",
      "Screwdriver Set",
      "Pliers Set",
      "Hammer",
      "Rubber Mallet",
      "Utility Knife",
      "Hacksaw",
      "File Set",
    ],
    SafetyEquipment: [
      "Work Gloves",
      "Refrigerant Gloves",
      "Safety Glasses",
      "Face Shield",
      "Dust Mask FFP2",
      "Gas Mask",
      "Ear Protection",
      "Hard Hat",
      "High Vis Vest",
      "Safety Boots",
      "Knee Pads",
      "First Aid Kit",
    ],
    LaddersAccess: [
      "Step Ladder 1.5m",
      "Step Ladder 2m",
      "Step Ladder 2.5m",
      "Step Ladder 3m",
      "Extension Ladder 4m",
      "Extension Ladder 6m",
      "Roof Ladder",
      "Platform Ladder",
      "Mobile Scaffold",
      "Scaffold Tower",
      "Cherry Picker",
    ],
    CleaningMaintenance: [
      "Coil Cleaning Spray",
      "Coil Cleaner Alkaline",
      "Coil Cleaner Acid",
      "Drain Pan Treatment Tablets",
      "AC Service Pump",
      "Condenser Cleaning Kit",
      "Air Filter Set",
      "Drain Cleaning Kit",
      "Mold Treatment Spray",
      "Lubricant Spray",
      "Compressor Oil",
    ],
  },

  Construction: {
    ExcavationEarthworks: [
      "Shovel",
      "Spade",
      "Pick Axe",
      "Mattock",
      "Digging Bar",
      "Trenching Shovel",
      "Post Hole Digger",
      "Hand Tamper",
      "Plate Compactor",
      "Jumping Jack Compactor",
      "Roller Compactor",
      "Mini Excavator",
      "Skid Steer",
    ],
    ConcreteTools: [
      "Concrete Mixer 130L",
      "Concrete Mixer 160L",
      "Concrete Mixer Electric",
      "Concrete Vibrator",
      "Poker Vibrator",
      "Vibrating Screed",
      "Bull Float",
      "Hand Float",
      "Steel Trowel",
      "Plastering Trowel",
      "Concrete Saw",
      "Diamond Blade 350mm",
      "Diamond Blade 400mm",
      "Core Drill 100mm",
      "Core Drill 150mm",
      "Core Drill 200mm",
      "Concrete Pump",
      "Concrete Breaker",
      "SDS Max Chisel",
      "Formwork Clamp",
      "Formwork Tie",
      "Prop Adjustable",
      "Prop Heavy Duty",
    ],
    MasonryTools: [
      "Brick Hammer",
      "Club Hammer",
      "Lump Hammer",
      "Bolster Chisel",
      "Brick Chisel",
      "Stone Chisel",
      "Pointing Trowel",
      "Brick Trowel",
      "Gauging Trowel",
      "Margin Trowel",
      "Bucket Trowel",
      "Grout Float",
      "Rubber Mallet",
      "Jointing Tool",
      "Brick Line",
      "Line Pins",
      "Brick Level",
      "Profile Poles",
      "Angle Grinder",
      "Diamond Cutting Disc",
      "Masonry Drill Bits",
    ],
    MeasuringTools: [
      "Tape Measure 5m",
      "Tape Measure 8m",
      "Tape Measure 10m",
      "Tape Measure 50m",
      "Steel Tape 30m",
      "Spirit Level 40cm",
      "Spirit Level 60cm",
      "Spirit Level 100cm",
      "Spirit Level 180cm",
      "Laser Level",
      "Rotating Laser Level",
      "Line Laser Level",
      "Laser Distance Meter",
      "Angle Finder",
      "Square",
      "Try Square",
      "Combination Square",
      "Plumb Bob",
      "Chalk Line",
      "Survey Staff",
      "Total Station",
    ],
    PowerTools: [
      "Makita Cordless Drill",
      "Makita SDS Rotary Hammer",
      "Makita SDS Max Demolition Hammer",
      "Makita Angle Grinder 125mm",
      "Makita Angle Grinder 230mm",
      "Makita Circular Saw",
      "Makita Reciprocating Saw",
      "Makita Jigsaw",
      "Makita Plate Compactor",
      "Bosch Cordless Drill",
      "Bosch SDS Hammer",
      "Bosch Circular Saw",
      "Hilti Rotary Hammer TE6",
      "Hilti Rotary Hammer TE60",
      "Hilti Demolition Hammer",
      "Hilti Core Drill",
      "Concrete Cutter",
      "Floor Grinder",
      "Wall Chaser",
      "Nailing Machine",
      "Rebar Cutter",
      "Rebar Bender",
    ],
    HandTools: [
      "Hammer Claw 500g",
      "Hammer Framing",
      "Sledgehammer 3kg",
      "Sledgehammer 5kg",
      "Pry Bar 600mm",
      "Pry Bar 900mm",
      "Crowbar",
      "Bolt Cutter",
      "Adjustable Wrench",
      "Spanner Set",
      "Pliers Set",
      "Screwdriver Set",
      "Utility Knife",
      "Hacksaw",
      "Hand Saw",
      "Tenon Saw",
      "Brick Saw",
      "File Set",
      "Punch Set",
      "Staple Gun",
      "Nail Gun",
      "Caulking Gun",
    ],
    LiftingRigging: [
      "Chain Hoist 1T",
      "Chain Hoist 2T",
      "Chain Hoist 5T",
      "Lever Hoist 1.5T",
      "Electric Chain Hoist",
      "Sling Chain 1T",
      "Sling Chain 2T",
      "Sling Belt 1T",
      "Sling Belt 2T",
      "Shackle 1T",
      "Shackle 2T",
      "Eyebolt M16",
      "Eyebolt M20",
      "Safety Hook",
      "Swivel Hook",
      "Wire Rope Sling",
      "Lifting Plate",
      "Pallet Forks",
      "Telehandler",
    ],
    LaddersAccess: [
      "Step Ladder 1.5m",
      "Step Ladder 2m",
      "Step Ladder 2.5m",
      "Step Ladder 3m",
      "Extension Ladder 4m",
      "Extension Ladder 5m",
      "Extension Ladder 6m",
      "Extension Ladder 8m",
      "Extension Ladder 10m",
      "Combination Ladder",
      "Platform Ladder",
      "Mobile Scaffold",
      "Scaffold Tower 4m",
      "Scaffold Tower 6m",
      "Scaffold Tower 8m",
      "Scaffold Boards",
      "Scaffold Coupler",
      "Scaffold Tube",
      "Safety Netting",
      "Safety Harness",
      "Fall Arrest System",
    ],
    SafetyEquipment: [
      "Hard Hat White",
      "Hard Hat Yellow",
      "Hard Hat Orange",
      "Safety Glasses",
      "Face Shield",
      "Ear Protection Plugs",
      "Ear Protection Muffs",
      "Dust Mask FFP1",
      "Dust Mask FFP2",
      "Dust Mask FFP3",
      "Work Gloves Leather",
      "Work Gloves Cut Resistant",
      "Safety Boots Steel Toe",
      "High Vis Vest",
      "High Vis Jacket",
      "Knee Pads",
      "Safety Harness Full Body",
      "Fall Arrest Lanyard",
      "First Aid Kit",
      "Fire Extinguisher",
      "Safety Barrier",
      "Safety Cone",
    ],
  },

  Welder: {
    WeldingMachines: [
      "MIG Welder 180A",
      "MIG Welder 250A",
      "MIG Welder 350A",
      "TIG Welder 200A AC/DC",
      "TIG Welder 315A",
      "MMA Welder 160A",
      "MMA Welder 250A",
      "Plasma Cutter 40A",
      "Plasma Cutter 60A",
      "Plasma Cutter 80A",
      "Spot Welder",
      "Stud Welder",
      "Multi-Process Welder",
      "Inverter Welder",
      "Engine Driven Welder",
    ],
    WeldingConsumables: [
      "MIG Wire ER70S-6 0.8mm",
      "MIG Wire ER70S-6 1.0mm",
      "MIG Wire ER70S-6 1.2mm",
      "MIG Wire Stainless 0.8mm",
      "MIG Wire Aluminium 1.0mm",
      "TIG Rod ER70S-2 2.4mm",
      "TIG Rod Stainless 2.4mm",
      "TIG Rod Aluminium 2.4mm",
      "Electrode E6013 2.5mm",
      "Electrode E6013 3.2mm",
      "Electrode E7018 3.2mm",
      "Electrode Stainless 3.2mm",
      "Electrode Cast Iron 3.2mm",
      "Flux Core Wire 0.9mm",
      "Flux Core Wire 1.2mm",
    ],
    WeldingGases: [
      "CO2 Gas Cylinder 20kg",
      "Argon Gas Cylinder 20L",
      "Argon Gas Cylinder 50L",
      "Mixed Gas Cylinder 20L",
      "Mixed Gas Cylinder 50L",
      "Oxygen Cylinder",
      "Acetylene Cylinder",
      "Nitrogen Cylinder",
      "Gas Regulator CO2",
      "Gas Regulator Argon",
      "Gas Regulator Oxygen",
      "Gas Regulator Acetylene",
      "Gas Hose 5m",
      "Gas Hose 10m",
      "Flow Meter",
    ],
    WeldingTools: [
      "Angle Grinder 115mm",
      "Angle Grinder 125mm",
      "Angle Grinder 230mm",
      "Grinding Disc 115mm",
      "Grinding Disc 125mm",
      "Cutting Disc 115mm",
      "Cutting Disc 125mm",
      "Flap Disc 115mm",
      "Wire Brush Wheel",
      "Wire Brush Hand",
      "Chipping Hammer",
      "Slag Hammer",
      "Welding Pliers",
      "Welding Clamp C",
      "Welding Clamp F",
      "Magnetic Clamp",
      "Welding Square",
      "Welding Table",
      "Ground Clamp",
      "MIG Gun MB25",
      "MIG Gun MB36",
      "TIG Torch 17",
      "TIG Torch 26",
      "Back Cap TIG",
      "Collet TIG",
      "Tungsten Electrode 2.4mm",
      "Tungsten Electrode 3.2mm",
      "Plasma Torch",
      "Plasma Consumables Kit",
    ],
    SafetyEquipment: [
      "Welding Helmet Auto Darkening",
      "Welding Helmet Fixed Shade",
      "Welding Jacket Leather",
      "Welding Jacket Cotton",
      "Welding Gloves MIG",
      "Welding Gloves TIG",
      "Welding Apron",
      "Welding Sleeves",
      "Safety Boots",
      "Ear Protection",
      "Respiratory Mask",
      "Fume Extractor",
      "Welding Screen",
      "Welding Blanket",
      "Fire Extinguisher CO2",
      "First Aid Kit",
    ],
    MeasuringTools: [
      "Welding Gauge",
      "Fillet Weld Gauge",
      "Weld Bead Gauge",
      "Tape Measure",
      "Steel Rule",
      "Square",
      "Angle Finder",
      "Marking Out Tools",
      "Center Punch",
      "Scribe",
      "Vernier Caliper",
      "Micrometer",
    ],
  },

  Carpenter: {
    HandSaws: [
      "Hand Saw General Purpose",
      "Tenon Saw",
      "Coping Saw",
      "Fret Saw",
      "Crosscut Saw",
      "Rip Saw",
      "Japanese Pull Saw",
      "Hacksaw",
      "Junior Hacksaw",
      "Bow Saw",
    ],
    PowerSaws: [
      "Circular Saw 165mm",
      "Circular Saw 190mm",
      "Cordless Circular Saw",
      "Track Saw",
      "Jigsaw Corded",
      "Jigsaw Cordless",
      "Reciprocating Saw",
      "Miter Saw 210mm",
      "Miter Saw 250mm",
      "Compound Miter Saw",
      "Sliding Miter Saw",
      "Table Saw",
      "Band Saw",
      "Scroll Saw",
      "Panel Saw",
    ],
    DrillingTools: [
      "Cordless Drill 18V",
      "Cordless Drill 12V",
      "Hammer Drill",
      "SDS Drill",
      "Right Angle Drill",
      "Drill Stand",
      "Drill Press",
      "Forstner Bit Set",
      "Spade Bit Set",
      "Auger Bit Set",
      "Hole Saw Set",
      "Brad Point Bit Set",
      "Countersink Set",
      "Plug Cutter Set",
    ],
    SandingFinishing: [
      "Orbital Sander",
      "Belt Sander",
      "Detail Sander",
      "Random Orbital Sander",
      "Disc Sander",
      "Spindle Sander",
      "Drum Sander",
      "Hand Sanding Block",
      "Sanding Paper 40 Grit",
      "Sanding Paper 80 Grit",
      "Sanding Paper 120 Grit",
      "Sanding Paper 180 Grit",
      "Sanding Paper 240 Grit",
      "Sanding Belt 40 Grit",
      "Sanding Belt 80 Grit",
    ],
    ChiselsPlanes: [
      "Chisel 6mm",
      "Chisel 12mm",
      "Chisel 19mm",
      "Chisel 25mm",
      "Chisel 38mm",
      "Chisel Set",
      "Mortice Chisel",
      "Skew Chisel",
      "Bench Plane No.4",
      "Bench Plane No.5",
      "Bench Plane No.7",
      "Block Plane",
      "Router Plane",
      "Rebate Plane",
      "Shoulder Plane",
      "Spokeshave",
      "Cabinet Scraper",
    ],
    Routers: [
      "Fixed Base Router",
      "Plunge Router",
      "Cordless Router",
      "Router Table",
      "Router Bit Set",
      "Straight Router Bit",
      "Roundover Router Bit",
      "Chamfer Router Bit",
      "Rabbet Router Bit",
      "Dovetail Router Bit",
      "Flush Trim Router Bit",
      "Cove Router Bit",
      "Edge Banding Trimmer",
    ],
    ClampingTools: [
      "F Clamp 150mm",
      "F Clamp 300mm",
      "F Clamp 600mm",
      "F Clamp 900mm",
      "G Clamp 50mm",
      "G Clamp 100mm",
      "G Clamp 150mm",
      "Bar Clamp 600mm",
      "Bar Clamp 900mm",
      "Bar Clamp 1200mm",
      "Pipe Clamp",
      "Corner Clamp",
      "Band Clamp",
      "Toggle Clamp",
      "Quick Release Clamp",
      "Parallel Jaw Clamp",
      "Cam Clamp",
      "Spring Clamp Set",
    ],
    MeasuringTools: [
      "Tape Measure 5m",
      "Tape Measure 8m",
      "Steel Rule 300mm",
      "Steel Rule 600mm",
      "Combination Square",
      "Try Square",
      "Speed Square",
      "Sliding Bevel",
      "Marking Gauge",
      "Mortice Gauge",
      "Dividers",
      "Compass",
      "Protractor",
      "Spirit Level",
      "Laser Level",
      "Profile Gauge",
      "Vernier Caliper",
      "Micrometer",
    ],
    HandTools: [
      "Claw Hammer 450g",
      "Pin Hammer",
      "Mallet Wooden",
      "Mallet Rubber",
      "Pry Bar",
      "Nail Punch Set",
      "Staple Gun",
      "Nail Gun Brad",
      "Nail Gun Framing",
      "Nail Gun Finish",
      "Biscuit Jointer",
      "Dowel Jig",
      "Pocket Hole Jig",
      "Screwdriver Set",
      "Utility Knife",
      "Marking Knife",
      "Awl",
    ],
    SafetyEquipment: [
      "Safety Glasses",
      "Face Shield",
      "Dust Mask FFP2",
      "Hearing Protection",
      "Work Gloves",
      "Safety Boots",
      "Knee Pads",
      "Dust Extractor",
      "Push Stick",
      "Featherboard",
      "First Aid Kit",
    ],
  },

  Painter: {
    BrushesRollers: [
      "Paint Brush 12mm",
      "Paint Brush 25mm",
      "Paint Brush 38mm",
      "Paint Brush 50mm",
      "Paint Brush 75mm",
      "Angled Brush 50mm",
      "Angled Brush 63mm",
      "Sash Brush 25mm",
      "Sash Brush 50mm",
      "Varnish Brush",
      "Radiator Brush",
      "Stippling Brush",
      "Paint Roller 100mm",
      "Paint Roller 180mm",
      "Paint Roller 230mm",
      "Roller Frame 100mm",
      "Roller Frame 180mm",
      "Roller Frame 230mm",
      "Roller Sleeve Short Pile",
      "Roller Sleeve Medium Pile",
      "Roller Sleeve Long Pile",
      "Roller Sleeve Foam",
      "Roller Tray 180mm",
      "Roller Tray 230mm",
      "Roller Tray Grid",
      "Paint Pad Set",
      "Corner Roller",
      "Pipe Roller",
    ],
    SprayEquipment: [
      "Airless Sprayer Electric",
      "Airless Sprayer Cordless",
      "HVLP Spray Gun",
      "Conventional Spray Gun",
      "Airbrush Kit",
      "Texture Sprayer",
      "Paint Pressure Pot",
      "Spray Tip 311",
      "Spray Tip 413",
      "Spray Tip 515",
      "Spray Tip 517",
      "Spray Tip 619",
      "Spray Tip Guard",
      "Spray Hose 15m",
      "Spray Hose 30m",
      "Gun Filter",
      "Pump Filter",
      "Fluid Section Repair Kit",
    ],
    SurfacePreparation: [
      "Orbital Sander",
      "Belt Sander",
      "Detail Sander",
      "Random Orbital Sander",
      "Pole Sander",
      "Hand Sanding Block",
      "Sanding Paper 40 Grit",
      "Sanding Paper 80 Grit",
      "Sanding Paper 120 Grit",
      "Sanding Paper 180 Grit",
      "Sanding Paper 240 Grit",
      "Sanding Mesh 120 Grit",
      "Sanding Mesh 180 Grit",
      "Abrasive Pad",
      "Wire Brush",
      "Scraper 75mm",
      "Scraper 100mm",
      "Scraper 150mm",
      "Filling Knife 75mm",
      "Filling Knife 100mm",
      "Filling Knife 150mm",
      "Stripping Knife",
      "Heat Gun",
      "Chemical Stripper",
      "Pressure Washer",
      "Wet and Dry Sandpaper",
    ],
    MaskingProtection: [
      "Masking Tape 19mm",
      "Masking Tape 25mm",
      "Masking Tape 38mm",
      "Masking Tape 50mm",
      "Masking Tape 75mm",
      "Low Tack Tape",
      "High Tack Tape",
      "Fine Line Tape",
      "Masking Film",
      "Protective Sheeting",
      "Drop Cloth Canvas",
      "Drop Cloth Plastic",
      "Masking Paper",
      "Masking Dispenser",
      "Corner Protector",
      "Edge Protector",
    ],
    MixingEquipment: [
      "Paint Mixer Drill Attachment",
      "Paddle Mixer",
      "Paint Kettle 5L",
      "Paint Kettle 10L",
      "Paint Strainer Bag",
      "Paint Strainer Cone",
      "Measuring Cup",
      "Mixing Stick",
      "Paint Can Opener",
      "Paint Pouring Spout",
      "Viscosity Cup",
    ],
    LaddersAccess: [
      "Step Ladder 1m",
      "Step Ladder 1.5m",
      "Step Ladder 2m",
      "Step Ladder 2.5m",
      "Step Ladder 3m",
      "Extension Ladder 4m",
      "Extension Ladder 6m",
      "Extension Ladder 8m",
      "Combination Ladder",
      "Platform Ladder",
      "Hop-Up Platform",
      "Stilts",
      "Scaffold Tower",
      "Mobile Scaffold",
      "Extension Pole 1.5m",
      "Extension Pole 2.4m",
      "Extension Pole 3.6m",
      "Extension Pole 4.8m",
    ],
    SafetyEquipment: [
      "Safety Glasses",
      "Chemical Goggles",
      "Dust Mask FFP1",
      "Dust Mask FFP2",
      "Solvent Respirator",
      "Paint Respirator",
      "Disposable Coveralls",
      "Work Gloves",
      "Chemical Gloves",
      "Safety Boots",
      "Hard Hat",
      "High Vis Vest",
      "First Aid Kit",
    ],
    MeasuringTools: [
      "Tape Measure 5m",
      "Spirit Level",
      "Laser Level",
      "Chalk Line",
      "Plumb Bob",
      "Wet Film Gauge",
      "Dry Film Gauge",
      "Hygrometer",
      "Thermometer",
      "DFT Gauge",
    ],
  },

  Warehouse: {
    ForkliftsHandling: [
      "Forklift Electric 1.5T",
      "Forklift Electric 2T",
      "Forklift Electric 3T",
      "Forklift LPG 2T",
      "Forklift LPG 3T",
      "Reach Truck",
      "Order Picker",
      "Counterbalance Forklift",
      "Pallet Truck Manual 2T",
      "Pallet Truck Electric 2T",
      "Pallet Truck Electric 2.5T",
      "Powered Stacker",
      "Manual Stacker",
      "Scissor Lift Table",
      "Lift Table Electric",
      "Drum Handler",
      "Drum Trolley",
      "Sack Truck",
      "Platform Truck",
      "Order Picker Trolley",
    ],
    Scanners: [
      "Barcode Scanner Handheld",
      "Barcode Scanner Wireless",
      "Barcode Scanner 2D",
      "QR Code Scanner",
      "RFID Reader",
      "RFID Handheld Scanner",
      "PDA Scanner Zebra TC52",
      "PDA Scanner Zebra TC57",
      "PDA Scanner Honeywell",
      "PDA Scanner Datalogic",
      "Fixed Barcode Scanner",
      "Presentation Scanner",
      "Wearable Scanner Ring",
      "Vehicle Mount Scanner",
      "Document Scanner",
      "Label Printer Zebra",
      "Label Printer Honeywell",
      "Label Printer Brother",
      "Thermal Label Printer",
      "Portable Label Printer",
    ],
    ShelvingSystems: [
      "Pallet Racking Frame 6m",
      "Pallet Racking Beam 2.7m",
      "Pallet Racking Beam 3.6m",
      "Pallet Racking Safety Pin",
      "Cantilever Racking",
      "Drive-In Racking",
      "Mezzanine Floor",
      "Shelving Unit Light Duty",
      "Shelving Unit Medium Duty",
      "Shelving Unit Heavy Duty",
      "Mobile Shelving",
      "Wire Shelving",
      "Bin Shelving",
      "Vertical Carousel",
      "Horizontal Carousel",
    ],
    SafetyEquipment: [
      "Safety Helmet",
      "High Vis Vest",
      "High Vis Jacket",
      "Safety Boots Steel Toe",
      "Safety Gloves",
      "Ear Protection",
      "Safety Glasses",
      "Forklift Safety Light",
      "Safety Barrier",
      "Safety Gate",
      "Rack Guard",
      "Column Protector",
      "Floor Marking Tape",
      "Safety Mirror",
      "First Aid Kit",
      "Fire Extinguisher",
      "Eye Wash Station",
      "Spill Kit",
    ],
    PackagingTools: [
      "Stretch Wrap Machine",
      "Stretch Wrap Manual",
      "Stretch Film",
      "Strapping Machine",
      "Strapping Tool Manual",
      "Strapping Tensioner",
      "Strapping Sealer",
      "Strapping Roll",
      "Tape Dispenser",
      "Packing Tape",
      "Bubble Wrap",
      "Foam Sheets",
      "Cardboard Boxes",
      "Packing Paper",
      "Box Cutter",
      "Staple Gun",
      "Glue Gun",
    ],
    MeasuringTools: [
      "Pallet Scale",
      "Floor Scale",
      "Bench Scale",
      "Counting Scale",
      "Tape Measure",
      "Vernier Caliper",
      "Laser Distance Meter",
      "Thermometer",
      "Hygrometer",
      "Torque Wrench",
    ],
    MaintenanceTools: [
      "Cordless Drill",
      "Angle Grinder",
      "Screwdriver Set",
      "Spanner Set",
      "Socket Set",
      "Hammer",
      "Mallet",
      "Pliers Set",
      "Utility Knife",
      "Hacksaw",
      "Pry Bar",
      "Cable Ties",
      "Safety Signs",
      "Padlocks",
      "Lock Out Tag Out Kit",
    ],
  },

  Logistics: {
    ScannersPDAs: [
      "PDA Scanner Zebra TC52",
      "PDA Scanner Zebra TC57",
      "PDA Scanner Zebra TC72",
      "PDA Scanner Zebra TC77",
      "PDA Scanner Honeywell CT60",
      "PDA Scanner Honeywell EDA51",
      "PDA Scanner Datalogic Memor",
      "Barcode Scanner Handheld",
      "Barcode Scanner Wireless Bluetooth",
      "Barcode Scanner 2D Imager",
      "RFID Reader Handheld",
      "RFID Reader Fixed",
      "Ring Scanner Zebra RS6000",
      "Ring Scanner Honeywell",
      "Vehicle Mount Computer",
      "Tablet Rugged",
      "Label Printer Zebra ZQ520",
      "Label Printer Zebra ZQ620",
      "Label Printer Honeywell",
      "Portable Label Printer",
    ],
    VehicleEquipment: [
      "GPS Tracker",
      "Dash Camera",
      "Reversing Camera",
      "Tail Lift Hydraulic",
      "Tail Lift Electric",
      "Load Securing Strap",
      "Load Securing Net",
      "Wheel Chock",
      "Reflective Triangle",
      "Fire Extinguisher",
      "First Aid Kit",
      "Breakdown Kit",
      "Tow Rope",
      "Jump Cables",
      "Torch LED",
      "High Vis Vest",
      "Safety Boots",
    ],
    HandlingEquipment: [
      "Pallet Truck Manual 2T",
      "Pallet Truck Electric",
      "Sack Truck",
      "Platform Truck",
      "Folding Sack Truck",
      "Stair Climbing Trolley",
      "Appliance Trolley",
      "Drum Trolley",
      "Cylinder Trolley",
      "Order Picker Cart",
      "Picking Cart",
      "Roller Conveyor",
      "Belt Conveyor",
      "Gravity Roller",
    ],
    PackagingTools: [
      "Stretch Wrap Machine",
      "Stretch Film Roll",
      "Strapping Machine",
      "Strapping Tool",
      "Strapping Roll PP",
      "Strapping Roll Steel",
      "Packing Tape Dispenser",
      "Packing Tape Roll",
      "Bubble Wrap Roll",
      "Foam Wrap Roll",
      "Cardboard Sheets",
      "Box Cutter Retractable",
      "Scissors Heavy Duty",
      "Glue Gun",
      "Hot Glue Sticks",
      "Staple Gun",
      "Corner Protectors",
      "Edge Protectors",
    ],
    SafetyEquipment: [
      "High Vis Vest Class 2",
      "High Vis Jacket Class 3",
      "Safety Boots Steel Toe",
      "Safety Gloves Cut Resistant",
      "Safety Glasses",
      "Ear Protection",
      "Hard Hat",
      "Knee Pads",
      "Back Support Belt",
      "Safety Barrier",
      "Floor Marking Tape",
      "Safety Mirror",
      "Safety Signs",
      "First Aid Kit",
      "Fire Extinguisher",
      "Spill Kit",
    ],
    MeasuringWeighing: [
      "Pallet Scale Platform",
      "Floor Scale Heavy Duty",
      "Bench Scale",
      "Parcel Scale",
      "Crane Scale",
      "Tape Measure",
      "Laser Distance Meter",
      "Thermometer Digital",
      "Data Logger Temperature",
      "Vernier Caliper",
    ],
  },

  FacilityManagement: {
    CleaningEquipment: [
      "Industrial Vacuum Cleaner",
      "Wet and Dry Vacuum",
      "Backpack Vacuum",
      "Ride-On Sweeper",
      "Walk-Behind Sweeper",
      "Floor Scrubber",
      "Ride-On Scrubber",
      "Pressure Washer Cold",
      "Pressure Washer Hot",
      "Steam Cleaner",
      "Mop and Bucket Set",
      "Microfiber Mop",
      "Floor Squeegee",
      "Window Cleaning Kit",
      "Window Squeegee",
      "Telescopic Pole",
      "Scrubbing Brush",
      "Cleaning Trolley",
    ],
    MaintenanceTools: [
      "Cordless Drill",
      "Hammer Drill",
      "Angle Grinder",
      "Screwdriver Set",
      "Spanner Set",
      "Pliers Set",
      "Socket Set",
      "Multimeter",
      "Cable Tester",
      "Voltage Tester",
      "Pipe Wrench",
      "Adjustable Wrench",
      "Tape Measure",
      "Spirit Level",
      "Hacksaw",
      "Utility Knife",
      "Caulking Gun",
      "Heat Gun",
      "Torch LED",
    ],
    GroundsEquipment: [
      "Lawn Mower Petrol",
      "Lawn Mower Electric",
      "Lawn Mower Ride-On",
      "Grass Strimmer",
      "Hedge Trimmer",
      "Leaf Blower",
      "Leaf Vacuum",
      "Garden Shears",
      "Pruning Saw",
      "Chainsaw Petrol",
      "Chainsaw Electric",
      "Chainsaw Battery",
      "Pressure Washer",
      "Garden Hose",
      "Sprinkler System",
      "Shovel",
      "Rake",
      "Fork",
      "Wheelbarrow",
    ],
    SafetyEquipment: [
      "High Vis Vest",
      "Safety Glasses",
      "Work Gloves",
      "Safety Boots",
      "Ear Protection",
      "Dust Mask",
      "Hard Hat",
      "Knee Pads",
      "First Aid Kit",
      "Fire Extinguisher",
      "Safety Signs",
      "Safety Barrier",
      "Wet Floor Sign",
      "Caution Sign",
    ],
    LaddersAccess: [
      "Step Ladder 1m",
      "Step Ladder 1.5m",
      "Step Ladder 2m",
      "Step Ladder 3m",
      "Extension Ladder 4m",
      "Extension Ladder 6m",
      "Combination Ladder",
      "Platform Ladder",
      "Mobile Scaffold",
      "Cherry Picker",
    ],
  },

  Medical: {
    DiagnosticEquipment: [
      "Blood Pressure Monitor",
      "Pulse Oximeter",
      "Thermometer Digital",
      "Infrared Thermometer",
      "ECG Machine",
      "Stethoscope",
      "Ophthalmoscope",
      "Otoscope",
      "Defibrillator AED",
      "Glucometer",
      "Peak Flow Meter",
      "Spirometer",
      "Ultrasound Portable",
    ],
    PatientCare: [
      "Wheelchair Standard",
      "Wheelchair Electric",
      "Walking Frame",
      "Walking Stick",
      "Crutches",
      "Hospital Bed",
      "Patient Hoist",
      "Patient Slide Sheet",
      "Pressure Mattress",
      "Bed Rails",
      "Over Bed Table",
      "IV Stand",
      "Drip Stand",
      "Infusion Pump",
      "Syringe Pump",
      "Feeding Pump",
      "Suction Machine",
      "Nebulizer",
      "Oxygen Concentrator",
      "Oxygen Cylinder",
    ],
    SurgicalTools: [
      "Surgical Scissors",
      "Forceps Set",
      "Retractor Set",
      "Scalpel Handle",
      "Needle Holder",
      "Suture Set",
      "Sterile Drapes",
      "Surgical Lights",
      "Operating Table",
      "Anesthesia Machine",
      "Electrosurgical Unit",
      "Laparoscopic Tower",
    ],
    SafetyEquipment: [
      "Latex Gloves Box",
      "Nitrile Gloves Box",
      "Surgical Mask Box",
      "N95 Respirator",
      "Face Shield",
      "Disposable Gown",
      "Sterile Gown",
      "Safety Glasses",
      "Shoe Covers",
      "Hair Net",
      "First Aid Kit",
      "Sharps Container",
      "Clinical Waste Bag",
      "Spill Kit",
    ],
    TransportEquipment: [
      "Ambulance Stretcher",
      "Scoop Stretcher",
      "Carry Chair",
      "Spine Board",
      "Head Immobilizer",
      "Cervical Collar",
      "Defibrillator Carry Bag",
      "Medical Bag",
      "Drug Kit",
      "Oxygen Bag",
    ],
  },

  General: {
    BasicHandTools: [
      "Hammer",
      "Screwdriver Set",
      "Pliers Set",
      "Wrench Set",
      "Utility Knife",
      "Tape Measure",
      "Spirit Level",
      "Hacksaw",
      "File Set",
      "Chisel Set",
      "Punch Set",
      "Hex Key Set",
    ],
    PowerTools: [
      "Cordless Drill",
      "Angle Grinder",
      "Circular Saw",
      "Jigsaw",
      "Reciprocating Saw",
      "Orbital Sander",
      "Heat Gun",
      "Rotary Hammer",
    ],
    MeasuringTools: [
      "Tape Measure 5m",
      "Tape Measure 8m",
      "Spirit Level",
      "Laser Level",
      "Laser Distance Meter",
      "Digital Multimeter",
      "Thermometer",
      "Vernier Caliper",
    ],
    SafetyEquipment: [
      "Safety Glasses",
      "Work Gloves",
      "Dust Mask",
      "Ear Protection",
      "Safety Boots",
      "High Vis Vest",
      "First Aid Kit",
      "Fire Extinguisher",
    ],
    StorageTransport: [
      "Tool Box",
      "Tool Bag",
      "Tool Cabinet",
      "Tool Trolley",
      "Parts Organizer",
      "Carry Case",
      "Backpack Tool Bag",
    ],
  },
};

export default toolCatalog;